### ISSUE TITLE
Library can't be compiled on unknown platforms

### ISSUE THREAD

**Issue by siepkes** [uutils/platform-info#47]
When trying to compile this library on an unknown platform the compiler errors out. This is an example of what happens on Illumos:

```
   Compiling platform-info v2.0.1 (/root/platform-info)
error[E0425]: cannot find value `HOST_OS_NAME` in module `crate::lib_impl`
  --> src/platform/unix.rs:57:53
   |
57 |             osname: OsString::from(crate::lib_impl::HOST_OS_NAME),
   |                                                     ^^^^^^^^^^^^ not found in `crate::lib_impl`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `platform-info` due to previous error
```

I've created the following PR which I think should fix the issue: https://github.com/uutils/platform-info/pull/46.

**Comment by tertsdiepraam** [comment]
In a separate PR, maybe it would be nice to add Illumos too!

**Comment by siepkes** [comment]
Was planning on doing that! But since you can't stack PR's in Github (and there is some overlap in them) I thought it would be better to get https://github.com/uutils/platform-info/pull/46 merged first.

**Comment by tertsdiepraam** [comment]
Agreed!
